### ISSUE TITLE
update from salt 2015.8 to 2016.3 would be welcome

### ISSUE THREAD

**Issue by sjorge** [TritonDataCenter/pkgsrc-legacy#375]
Lots of illumos (and SmartOS) specific goodness in the new one :)

**Comment by sjorge** [comment]
Any progress on this 2015.8 is pretty meh compared to 2016.3

**Comment by jperkin** [comment]
Could you try

```
pkg_add http://us-east.manta.joyent.com/pkgsrc/public/tmp/salt-2016.3.1.tgz
```

in a 2016Q2 x86_64 zone and let me know if it works ok? Thanks.

**Comment by sjorge** [comment]
Works fine for me! I installed the package and then did my basic minion rollout, worked without a hitch:

``` yaml
local:
----------
          ID: locale::generate_nl_BE.UTF-8
    Function: locale.present
        Name: nl_BE.UTF-8
      Result: True
     Comment: Locale nl_BE.UTF-8 is already present
     Started: 19:42:49.877398
    Duration: 237.067 ms
     Changes:
----------
          ID: locale::generate_en_US.UTF-8
    Function: locale.present
        Name: en_US.UTF-8
      Result: True
     Comment: Locale en_US.UTF-8 is already present
     Started: 19:42:50.114865
    Duration: 167.518 ms
     Changes:
----------
          ID: locale::system
    Function: locale.system
        Name: en_US.UTF-8
      Result: True
     Comment: System locale en_US.UTF-8 already set
     Started: 19:42:50.284212
    Duration: 67.278 ms
     Changes:
----------
          ID: time::timezone
    Function: timezone.system
        Name: Europe/Brussels
      Result: True
     Comment: Timezone Europe/Brussels already set, UTC already set to Europe/Brussels
     Started: 19:42:50.354163
    Duration: 1.644 ms
     Changes:
----------
          ID: network::resolv.conf
    Function: file.managed
        Name: /etc/resolv.conf
      Result: True
     Comment: File /etc/resolv.conf is in the correct state
     Started: 19:42:50.361508
    Duration: 55.013 ms
     Changes:
----------
          ID: network::hosts
    Function: file.managed
        Name: /etc/hosts
      Result: True
     Comment: File /etc/hosts is in the correct state
     Started: 19:42:50.416683
    Duration: 57.923 ms
     Changes:
----------
          ID: network.route.inet4::net0-0.0.0.0/0
    Function: cmd.run
        Name: /usr/sbin/route -p add -inet 0.0.0.0/0 172.16.30.1 -ifp net0 -static
      Result: True
     Comment: unless execution succeeded
     Started: 19:42:50.475568
    Duration: 67.847 ms
     Changes:
----------
          ID: network.route.inet6::net0-::/0
    Function: cmd.run
        Name: /usr/sbin/route -p add -inet6 ::/0 2001:6f8:1480:30::1 -ifp net0 -static
      Result: True
     Comment: unless execution succeeded
     Started: 19:42:50.543807
    Duration: 65.593 ms
     Changes:
----------
          ID: sysinfo::motd
    Function: file.managed
        Name: /etc/motd
      Result: True
     Comment: File /etc/motd is in the correct state
     Started: 19:42:50.610026
    Duration: 124.85 ms
     Changes:
----------
          ID: account.shell::/opt/local/bin/zsh
    Function: pkg.installed
        Name: zsh
      Result: True
     Comment: Package zsh is already installed
     Started: 19:42:51.942537
    Duration: 269.277 ms
     Changes:
----------
          ID: account.shell::/opt/local/bin/bash
    Function: pkg.installed
        Name: bash
      Result: True
     Comment: Package bash is already installed
     Started: 19:42:52.212111
    Duration: 11.854 ms
     Changes:
----------
          ID: account.root
    Function: user.present
        Name: root
      Result: True
     Comment: User root is present and up to date
     Started: 19:42:52.225982
    Duration: 57.814 ms
     Changes:
----------
          ID: account.group::sysadmin
    Function: group.present
        Name: sysadmin
      Result: True
     Comment: Group sysadmin is present and up to date
     Started: 19:42:52.284737
    Duration: 0.731 ms
     Changes:
----------
          ID: account.group::user
    Function: group.present
        Name: user
      Result: True
     Comment: Group user is present and up to date
     Started: 19:42:52.285597
    Duration: 0.457 ms
     Changes:
----------
          ID: account.group::service
    Function: group.present
        Name: service
      Result: True
     Comment: Group service is present and up to date
     Started: 19:42:52.286192
    Duration: 0.455 ms
     Changes:
----------
          ID: account.sudo
    Function: pkg.installed
        Name: sudo
      Result: True
     Comment: Package sudo is already installed
     Started: 19:42:52.286772
    Duration: 12.115 ms
     Changes:
----------
          ID: account.user::sjorge
    Function: user.present
        Name: sjorge
      Result: True
     Comment: User sjorge is present and up to date
     Started: 19:42:52.299027
    Duration: 61.929 ms
     Changes:
----------
          ID: account.user::sjorge
    Function: ssh_auth.present
        Name: AAAAB3NzaC1yc2EAAAABIwAAAQEA7st+KRfqBdNGhyEDBxzssIv9xVH7yl5fMOUVHLk1VTmpOyCpYi/+yI2QsMIdndFqWK7rM4xgCK+osKP2kj/edy7FTzi78c6vP3Jli+Dt17ZgC/CxlEReJe+o0/l1tdWbl+kg9nB0DtGMSvntFcIdQmn5ZiPOzGrLKvI9Tngt0BWLrYXlQzBkq65MBbizoxkErR4nHppt9mLeTR9ZY6YsRi2roVVNUJWKat/RvC6ncPs4+Mpy56330MA+40cGlFFlucQnlzIx6ghey13P+RdZYuexJP6JunyZOntCcieahNJ+FklCEeeVChhjO0tFtioz49udCEOxo9kmfDUOiqi61w==
      Result: True
     Comment: The authorized host key AAAAB3NzaC1yc2EAAAABIwAAAQEA7st+KRfqBdNGhyEDBxzssIv9xVH7yl5fMOUVHLk1VTmpOyCpYi/+yI2QsMIdndFqWK7rM4xgCK+osKP2kj/edy7FTzi78c6vP3Jli+Dt17ZgC/CxlEReJe+o0/l1tdWbl+kg9nB0DtGMSvntFcIdQmn5ZiPOzGrLKvI9Tngt0BWLrYXlQzBkq65MBbizoxkErR4nHppt9mLeTR9ZY6YsRi2roVVNUJWKat/RvC6ncPs4+Mpy56330MA+40cGlFFlucQnlzIx6ghey13P+RdZYuexJP6JunyZOntCcieahNJ+FklCEeeVChhjO0tFtioz49udCEOxo9kmfDUOiqi61w== is already present for user sjorge
     Started: 19:42:52.361974
    Duration: 4.136 ms
     Changes:
----------
          ID: account.sudo::sjorge
    Function: file.managed
        Name: /opt/local/etc/sudoers.d/sjorge
      Result: True
     Comment: File /opt/local/etc/sudoers.d/sjorge is in the correct state
     Started: 19:42:52.367208
    Duration: 2.285 ms
     Changes:
----------
          ID: account.sudo::sjorge
    Function: cmd.wait
        Name: usermod -P 'Primary Administrator' sjorge
      Result: True
     Comment:
     Started: 19:42:52.370397
    Duration: 0.476 ms
     Changes:
----------
          ID: account.profile.default::sjorge
    Function: archive.extracted
        Name: /home/sjorge
      Result: True
     Comment: /home/sjorge/.salt/profile-default already exists
     Started: 19:42:52.797868
    Duration: 0.594 ms
     Changes:
----------
          ID: account.profile.shell::sjorge
    Function: archive.extracted
        Name: /home/sjorge
      Result: True
     Comment: /home/sjorge/.salt/profile-shell already exists
     Started: 19:42:52.799077
    Duration: 0.48 ms
     Changes:
----------
          ID: account.profile.user::sjorge
    Function: archive.extracted
        Name: /home/sjorge
      Result: True
     Comment: /home/sjorge/.salt/profile-user already exists
     Started: 19:42:52.800177
    Duration: 0.528 ms
     Changes:
----------
          ID: account.profile::sjorge
    Function: file.directory
        Name: /home/sjorge
      Result: True
     Comment: Directory /home/sjorge is in the correct state
     Started: 19:42:52.803650
    Duration: 10.505 ms
     Changes:
----------
          ID: account.profile.default::sjorge
    Function: file.managed
        Name: /home/sjorge/.salt/profile-default
      Result: True
     Comment: File /home/sjorge/.salt/profile-default is in the correct state
     Started: 19:42:52.818090
    Duration: 1.766 ms
     Changes:
----------
          ID: account.profile.shell::sjorge
    Function: file.managed
        Name: /home/sjorge/.salt/profile-shell
      Result: True
     Comment: File /home/sjorge/.salt/profile-shell is in the correct state
     Started: 19:42:52.823769
    Duration: 1.699 ms
     Changes:
----------
          ID: account.profile.user::sjorge
    Function: file.managed
        Name: /home/sjorge/.salt/profile-user
      Result: True
     Comment: File /home/sjorge/.salt/profile-user is in the correct state
     Started: 19:42:52.829384
    Duration: 1.7 ms
     Changes:
----------
          ID: package.repo.key::pkg.blackdot.be
    Function: file.managed
        Name: /opt/local/etc/gnupg/keys/pbd.key
      Result: True
     Comment: File /opt/local/etc/gnupg/keys/pbd.key is in the correct state
     Started: 19:42:52.831213
    Duration: 23.68 ms
     Changes:
----------
          ID: package.repo.key::pkg.blackdot.be
    Function: cmd.wait
        Name: gpg --no-default-keyring --keyring /opt/local/etc/gnupg/pkgsrc.gpg --import /opt/local/etc/gnupg/keys/pbd.key
      Result: True
     Comment:
     Started: 19:42:52.856795
    Duration: 0.86 ms
     Changes:
----------
          ID: package.repo::pkg.blackdot.be
    Function: file.append
        Name: /opt/local/etc/pkgin/repositories.conf
      Result: True
     Comment: File /opt/local/etc/pkgin/repositories.conf is in correct state
     Started: 19:42:52.858895
    Duration: 4.574 ms
     Changes:
----------
          ID: package.repo::pkg.blackdot.be
    Function: cmd.wait
        Name: pkgin -fy up
      Result: True
     Comment:
     Started: 19:42:52.864395
    Duration: 0.432 ms
     Changes:
----------
          ID: package::tmux
    Function: pkg.installed
        Name: tmux
      Result: True
     Comment: Package tmux is already installed
     Started: 19:42:52.864949
    Duration: 11.748 ms
     Changes:
----------
          ID: package::watch
    Function: pkg.installed
        Name: watch
      Result: True
     Comment: Package watch is already installed
     Started: 19:42:52.876822
    Duration: 11.507 ms
     Changes:
----------
          ID: package::schedule-upgrade
    Function: schedule.present
      Result: True
     Comment: Job package::schedule-upgrade in correct state
     Started: 19:42:52.888454
    Duration: 10.136 ms
     Changes:
----------
          ID: common.grains::sync
    Function: grains.absent
        Name: states
      Result: True
     Comment: Grain states does not exist
     Started: 19:42:52.898718
    Duration: 0.515 ms
     Changes:
----------
          ID: certificate::packages:
    Function: pkg.installed
        Name: openssl
      Result: True
     Comment: Package openssl is already installed
     Started: 19:42:52.899353
    Duration: 11.567 ms
     Changes:
----------
          ID: certificate::packages:
    Function: pkg.installed
        Name: perl
      Result: True
     Comment: Package perl is already installed
     Started: 19:42:52.911045
    Duration: 11.515 ms
     Changes:
----------
          ID: certificate::truststore
    Function: file.directory
        Name: /opt/local/etc/openssl/certs
      Result: True
     Comment: Directory /opt/local/etc/openssl/certs is in the correct state
     Started: 19:42:52.922682
    Duration: 0.8 ms
     Changes:
----------
          ID: certificate::truststore
    Function: x509.pem_managed
        Name: /opt/local/etc/openssl/certs/internal-ca.crt
      Result: True
     Comment: The file is already in the correct state
     Started: 19:42:52.924345
    Duration: 0.626 ms
     Changes:
----------
          ID: certificate::truststore
    Function: cmd.wait
        Name: /opt/local/bin/c_rehash
      Result: True
     Comment:
     Started: 19:42:52.925597
    Duration: 0.41 ms
     Changes:
----------
          ID: certificate::keystore
    Function: file.directory
        Name: /opt/local/etc/pki
      Result: True
     Comment: Directory /opt/local/etc/pki is in the correct state
     Started: 19:42:52.926127
    Duration: 0.761 ms
     Changes:
----------
          ID: salt.minion::config
    Function: file.managed
        Name: /salt/config/minion
      Result: True
     Comment: File /salt/config/minion is in the correct state
     Started: 19:42:52.927007
    Duration: 44.404 ms
     Changes:
----------
          ID: salt.minion::config.d
    Function: file.directory
        Name: /salt/config/minion.d
      Result: True
     Comment: Directory /salt/config/minion.d is in the correct state
     Started: 19:42:52.971545
    Duration: 1.091 ms
     Changes:
----------
          ID: salt.minion::smtp
    Function: file.managed
        Name: /salt/config/minion.d/smtp.conf
      Result: True
     Comment: File /salt/config/minion.d/smtp.conf is in the correct state
     Started: 19:42:52.973508
    Duration: 58.129 ms
     Changes:
----------
          ID: salt.minion::wrapper
    Function: file.symlink
        Name: /usr/local/bin/salt-call
      Result: True
     Comment: Symlink /usr/local/bin/salt-call is present and owned by root:root
     Started: 19:42:53.031772
    Duration: 2.856 ms
     Changes:
----------
          ID: salt.minion::schedule-apply
    Function: schedule.present
      Result: True
     Comment: Job salt.minion::schedule-apply in correct state
     Started: 19:42:53.034754
    Duration: 8.97 ms
     Changes:
----------
          ID: ssh.server::config
    Function: file.managed
        Name: /etc/ssh/sshd_config
      Result: True
     Comment: File /etc/ssh/sshd_config is in the correct state
     Started: 19:42:53.043849
    Duration: 58.974 ms
     Changes:
----------
          ID: ssh.server::service
    Function: service.running
        Name: ssh
      Result: True
     Comment: The service ssh is already running
     Started: 19:42:53.103676
    Duration: 423.128 ms
     Changes:
----------
          ID: salt.minion::service
    Function: service.running
        Name: salt:minion
      Result: True
     Comment: The service salt:minion is already running
     Started: 19:42:53.529126
    Duration: 402.248 ms
     Changes:

Summary for local
-------------
Succeeded: 49
Failed:     0
-------------
Total states run:     49
```
